# Generated by Django 2.0.5 on 2018-05-18 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='static-storage/user/profile_pic', verbose_name='Profile picture')),
                ('phone_no', models.CharField(blank=True, max_length=17, verbose_name='Phone No.')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
