# Generated by Django 2.0.5 on 2018-05-22 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Quick summary of your reminder. (Can be empty)', max_length=256, verbose_name='Title')),
                ('slug', models.SlugField(max_length=256, verbose_name='Slug')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('timed_on', models.DateTimeField(verbose_name='Timed on')),
                ('reminded_count', models.PositiveIntegerField(verbose_name='Reminded count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
