# Generated by Django 2.0.5 on 2018-05-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(help_text='Quick summary of your reminder.', max_length=256, verbose_name='Title'),
        ),
    ]
