# Generated by Django 2.0.5 on 2018-05-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20180522_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='slug',
            field=models.SlugField(max_length=256, verbose_name='Slug'),
        ),
    ]
