# Generated by Django 2.0.5 on 2018-05-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_auto_20180526_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['timed_on']},
        ),
    ]
